package org.sch.issecurity.iam.tools.ADSync.jpa;

import org.sch.issecurity.iam.tools.ADSync.entity.ADUserCLEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Created by XiChen on 2/22/2017.
 */

import org.sch.issecurity.iam.tools.ADSync.entity.ADUserCLEntity;
        import org.springframework.data.jpa.repository.JpaRepository;
        import org.springframework.stereotype.Repository;

/**
 * A repository managing {@link ADUserCLEntity} entities. Implementation will be generated by Spring Data JPA.
 */
@Repository
public interface ADUserCLRepository extends JpaRepository<ADUserCLEntity, Long> {

}