package org.sch.issecurity.iam.tools.ADSync.jpa;

/**
 * Created by XiChen on 2/20/2017.
 */

import org.sch.issecurity.iam.tools.ADSync.entity.ADUserEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * A repository managing {@link ADUserEntity} entities. Implementation will be generated by Spring Data JPA.
 */
@Repository
public interface ADUserRepository extends JpaRepository<ADUserEntity, Long> {

    ADUserEntity findByObjectGUID(String objectGUID);
}