package org.sch.issecurity.iam.tools.ADSync.jpa;

/**
 * Created by XiChen on 2/20/2017.
 */
import org.sch.issecurity.iam.tools.ADSync.entity.DomainControllerAffiliation;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * A JPA repository managing {@link DomainControllerAffiliation} entities. The implementation is generated by Spring Data
 * JPA when the Spring context is initialized.
 */
@Repository
public interface DomainControllerAffiliationRepository extends JpaRepository<DomainControllerAffiliation, String> {
}